### ISSUE TITLE
syntax for creating sidechain pseudoatoms for selected residues

### ISSUE THREAD

**Issue by goji-patai** [Pymol-Scripts/Pymol-script-repo#120]
Hi,
   I am hoping you can point me in the right direction.  I am reading a PDB as follows:
```py
path = 'TO PATH'
for filename in glob.glob(os.path.join(path, '*.pdb)):
    cmd.load(filename)  # use the name of your pdb file
    stored.residues = []
    cmd.iterate('name ca', 'stored.residues.append((resn))')
    #print (stored.residues)
```
Then I want to create a sidechain pseudoatom and save its coordinate in an array along the lines ...
```py
    stored_residues_sidechain_PS = []
    for i in stored.residues:
        cmd.select ('resn %s' % i)
        stored_residues_sidechain_PS.append(sidechaincenters [ '(sele)' [2]])
```
but I am having difficulty with the correct syntax to use for sidechaincenters.  Please point me in the right direction.
Thank you

**Comment by speleo3** [comment]
You might find this useful:
https://pymolwiki.org/index.php/Sidechaincenters

**Comment by goji-patai** [comment]
Hi Thomas,
   Thank you.  That was good guidance. I can now calculate the
Sidechaincenters.  Working on manipulating the scc object.

Best,
G
