### ISSUE TITLE
Cyspka- "error empty selection"

### ISSUE THREAD

**Issue by JackSuitor** [Pymol-Scripts/Pymol-script-repo#125]
Running the example script included with the cyspka source code results in the following messages for me: 
```
# Hello, PyMOLers. It should take around 1 minute per residue.
# molecule: 4AKE-A , chain: A, residue: 71.300 18, pH: 7.2 
 Error: Empty Selection
```
I have been modifying the code to try and determine where the issue is. Print messages inserted before the `if NotPopNr == 0:` code will run. However, if any code following `if NotPopNr == 0:` is added, then the script will not run at all and I receive a syntax error. 

Any help would be much appreciated.

**Comment by JackSuitor** [comment]
Through iterative troubleshooting, I have found that the command causing the error message is cmd.get_atom_coords(), which is found in line 176.

**Comment by speleo3** [comment]
For the record:

https://github.com/Pymol-Scripts/Pymol-script-repo/blob/ab0762d7cbf5fb004c28791b213ebfc259498345/cyspka.py#L176

**Comment by speleo3** [comment]
Fixed in https://github.com/schrodinger/pymol-open-source/pull/323
