### ISSUE TITLE
Is there an api implementation like cmd.movie_fade()?

### ISSUE THREAD

**Issue by mce13** [Pymol-Scripts/Pymol-script-repo#126]
Hi there,

quick question. Is there an api implementation of movie_fade available? `cmd.movie_fade(...)` gives me an `AttributeError: module 'pymol.cmd' has no attribute 'movie_fade'`

Thanks a lot in advance,

mce13

**Comment by speleo3** [comment]
Try this:
```py
movie_fade = cmd.keyword["movie_fade"][0]
movie_fade(...)
```
