### ISSUE TITLE
Script to convert current visual ligand-protein complex to python code

### ISSUE THREAD

**Issue by rez3vil** [Pymol-Scripts/Pymol-script-repo#138]
Hi,

I am looking for script or nay module which will convert whatever changes you made to your protein and ligand to make it look pretty, it will convert all these changes all at once to python code, so that it can be applied to another complex. Is there any such script available?

Thank you.

**Comment by pslacerda** [comment]
Hi, the most similar feature would be use presets like "technical" or "pretty" on action (A) menu. You can record a log of your modifications with the `File > Log File > Open/Close` and adapt the resulting log.txt into a [.pml script](https://pymolwiki.org/index.php/Pml) which can aid on your quest.

I don't know how to do exactly what you're asking.
