### ISSUE TITLE
tmalign update

### ISSUE THREAD

**Issue by nemethzb** [Pymol-Scripts/Pymol-script-repo#143]
Hi,
I found tmalign.py not compatible with the 2022/4/12 version of the TM-align source code in C++. Changing line 155 in tmalign.py to:
        elif line.lower().startswith(' -------- rotation matrix') or line.lower().startswith('------ the rotation matrix'):
fixed the issue.
Kind regards.

**Comment by pslacerda** [comment]
Hi, just changed the string. Didn't tested, just checked the current [TM-align source code](https://zhanggroup.org/TM-align/).
