### ISSUE TITLE
how to refresh the plugin in the pmg/startup

### ISSUE THREAD

**Issue by autodataming** [Pymol-Scripts/Pymol-script-repo#89]
I open the pymol, then I revised the plugin in the "pmg/startup" directory, how can I refresh the plugin without closing and reopen the pymol? can you give me some suggestions?

**Comment by speleo3** [comment]
You should have (limited) success by using the `reload()` function: https://docs.python.org/2/library/functions.html#reload

For example to reload the APBS plugin, type into the PyMOL command line:

    import pmg_tk
    reload(pmg_tk.startup.apbs_tools)

**Comment by autodataming** [comment]
Thank You. I have tried it. But it failed.
For example, I write a plugin named by "PyPocket_plugin".
Then I open the Pymol, I click the "PyPocket_plugin" in the menubutton "Plugin", and then open a toplevel window, If I find the title of the window has a little error, then I revise the title in the script "PyPocket_plugin". Final, I type the command
'''
PyMOL>import pmg_tk
PyMOL>reload(pmg_tk.startup.PyPocket_plugin)
'''
and open the Toplevel of the plugin, but the title of the Toplvel still be unchanged.

**Comment by autodataming** [comment]
I come across another problems.  I uninstall the 'PyPocket_plugin' in the Plugin Manger, then I found all the files about the Plugin were disappeared. Can I got these files about the PyPocket_plugin again?

**Comment by autodataming** [comment]
Thank you very much, I have successed to refresh the Plugin. 
If I change the  PyPocket/files.py, I think I should reload the file revised.
reload(pmg_tk.startup.PyPocket.PredictGui)
