### ISSUE TITLE
how can the sphere point in the cgo object  be selected?

### ISSUE THREAD

**Issue by autodataming** [Pymol-Scripts/Pymol-script-repo#91]
I cteate the cgo object consists of many sphere point, I want to select two point,and use the distance command to label the distance? Is it  available?

**Comment by aloctavodia** [comment]
I think a CGO object behaves like a single, indivisible entity, is this true @speleo3? 
BTW, @autodataming this type of questions are better suited for the PyMOL [mailing list](http://www.mail-archive.com/pymol-users@lists.sourceforge.net/info.html)

**Comment by speleo3** [comment]
CGOs are simple graphical entities which can't be selected. If you want to measure distances, I recommend to work with pseudoatoms instead.
