### ISSUE TITLE
Plugin manager updates

### ISSUE THREAD

**Issue by StephanHeijl** [Pymol-Scripts/Pymol-script-repo#92]
Hello, I'm developing a plugin for PyMol and I would like my users to get the latest version of the plugin whenever it is updated. I was unable to find online whether or not users of PyMol receive messages or have their plugins updated automatically when they are changed in the repository. Could you shed some light on this?

Kind regards.

**Comment by aloctavodia** [comment]
Currently there are not update messages AFAIK

**Comment by pslacerda** [comment]
The old version of my plugin `drugpy` does something like this. It has a button "Update" that uses pip to upgrade the version of the plugin to the latest.

https://github.com/labimm/DRUGpy/blob/master/scripts/DRUGpy.py

It implements the plugin's features in a pypi package and calls the current Python's executable invoking `pip` to upgrade.
