### ISSUE TITLE
extra_fit does not report rms if method=cealign

### ISSUE THREAD

**Issue by hongbo-zhu-cn** [Pymol-Scripts/Pymol-script-repo#93]
Hi, Thomas, 

The current version of extra_fit will not report rms for each alignment result because cealign returns a dict. 
In PyMOL version 1.8.4, extra_fit prints only model names (see below). I would like to suggest an improvement because:

1. three alignment methods are suggested in the help (align, super and cealign). RMS is not reported only if cealign is set as the method.
2. In PyMOL 1.8, the **ailgnto** function uses extra_fit and set method="cealign". So it does not print rms information, either. 

current code:
```
                if not quiet:
                    if _self.is_sequence(x):
                        print('%-20s RMS = %8.3f (%d atoms)' % (model, x[0], x[1]))
                    elif isinstance(x, float):
                        print('%-20s RMS = %8.3f' % (model, x))
                    else:
                        print('%-20s' % (model,))
```

suggested improvement
```
                if not quiet:
                    if _self.is_sequence(x):
                        print('%-20s RMS = %8.3f (%d atoms)' % (model, x[0], x[1]))
                    elif isinstance(x, float):
                        print('%-20s RMS = %8.3f' % (model, x))
                    elif _self.is_dict(x):
                        if 'RMSD' in x:
                            print('%-20s RMS = %8.3f' % (model, x['RMSD']))
                        else:
                            print('%-20s' % (model,))  
                    else:
                        print('%-20s' % (model,))
```

**Comment by speleo3** [comment]
Hi Hongbo, thanks for the great suggestion! There are several copies of the `extra_fit` implementation floating around, one here in [Pymol-script-repo](https://github.com/Pymol-Scripts/Pymol-script-repo), one in [psico](https://github.com/speleo3/pymol-psico), and one in PyMOL itself. I will update them all according to your suggestion.
